#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm run import-test
npm run headless-browser-test
npm run build-commonjs
npm run require-test
npm run build-docs
# convert to es class, then enable
#npm run build-types
npm run add-generated-files-to-commit
